<?php

namespace PSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceLineItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceLineItemsRepository extends EntityRepository
{
}
