<?php

namespace PSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends EntityRepository
{

    public function test(){

        $stmt = $this->getEntityManager()
            ->getConnection()
            -> prepare('
                SELECT
                *
                FROM
                invoices
                INNER JOIN
                InvoiceLineItems
                ON
                Invoices.invoice_num=InvoiceLineItems.invoice_num
                INNER JOIN
                Products
                ON
                InvoiceLineItems.product_id=products.product_id
                ');
        //$stmt = bindValue('',$);
        $stmt->execute();
        return $invoices = $stmt->fetchAll();


    }
}
