<?php

namespace PSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends EntityRepository
{
}
